import Head from 'next/head'
import Nav from '../components/Nav'
import { ChevronDownIcon } from '@chakra-ui/icons'
import { Button, Center, Flex, Menu, MenuButton, MenuItem, MenuList, Table, Td, Th, Thead, Tr } from '@chakra-ui/react'
import Router from 'next/router'
import React, { useEffect, useState } from 'react'

export default function Home() {
  const [users, setUsers] = useState([])
  const [msgLogs, setMsgLogs] = useState([])

  // function to get data from the Users.json file
  function getUsers() {
    fetch(`${process.env.NEXT_PUBLIC_BASE}/api/users`)
      .then(res => res.json())
      .then(data => setUsers(data))
  }
    // function to get data from the Msglogs.json file
  function getMsgLogs() {
    fetch(`${process.env.NEXT_PUBLIC_BASE}/api/msglog`)
      .then(res => res.json())
      .then(data => setMsgLogs(data.reverse()))
  }

  // function to send porps to the next page
  function sendProps(Fname, Lname, phone_no, gender, email) {
    Router.push({
      pathname: "/userDetail",
      query: {
        name: `${Fname} ${Lname}`,
        phone_no,
        gender,
        email
      }
    })
  }

  useEffect(() => {
    getUsers()
    getMsgLogs()
  }, [])

  return (
    <div >
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Nav>
          <Center margin={20}>
            <Flex gap={40}>

              {/* first menu showing contact list */}
              <Menu >
                <MenuButton as={Button} rightIcon={<ChevronDownIcon />}>
                  Contacts
                </MenuButton>
                <MenuList className='menu' overflow={"auto"} maxH={"250px"} >
                  {
                    users?.map(user => (
                      <MenuItem
                        onClick={() => {
                          sendProps(user.first_name, user.last_name, user.phone_no, user.gender, user.email)
                        }}
                        key={user.id}>
                        {`${user.first_name} ${user.last_name}`}
                      </MenuItem>
                    ))
                  }
                </MenuList>
              </Menu>

              {/* second list showing all previously send messages */}
              <Menu>
                <MenuButton as={Button} rightIcon={<ChevronDownIcon />}>
                  Messages
                </MenuButton>
                <MenuList className='menu' overflow={"auto"} maxH={"250px"} >
                  <Table>
                    <Thead>
                      <Tr>
                        <Th>Name</Th>
                        <Th>OTP</Th>
                        <Th >Time</Th>
                        <Th >Status</Th>
                      </Tr>
                    </Thead>
                    {
                      msgLogs?.map((msg, i) => (
                        <Tr key={i}>
                          <Td> {msg.name}</Td>
                          <Td>{msg.msg}</Td>
                          <Td >{msg.timestamp}</Td>
                          <Td >{msg.status}</Td>
                        </Tr>
                      ))
                    }
                  </Table>
                </MenuList>
              </Menu>
            </Flex>
          </Center>
        </Nav>
      </main>
      <footer>
      </footer>
    </div>
  )
}
